<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FootballRegistrySeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $confederations = [
            ['id' => 1, 'code' => 'CONCACAF', 'name' => 'CONCACAF', 'active' => true],
            ['id' => 2, 'code' => 'CONMEBOL', 'name' => 'CONMEBOL', 'active' => true],
            ['id' => 3, 'code' => 'UEFA', 'name' => 'UEFA', 'active' => true],
        ];

        $countries = [
            ['id' => 1, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Anguilla', 'iso2' => 'AI', 'iso3' => 'AIA', 'active' => true],
            ['id' => 2, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'active' => true],
            ['id' => 3, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Aruba', 'iso2' => 'AW', 'iso3' => 'ABW', 'active' => true],
            ['id' => 4, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'active' => true],
            ['id' => 5, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'active' => true],
            ['id' => 6, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'active' => true],
            ['id' => 7, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Bermuda', 'iso2' => 'BM', 'iso3' => 'BMU', 'active' => true],
            ['id' => 8, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'British Virgin Islands', 'iso2' => 'VG', 'iso3' => 'VGB', 'active' => true],
            ['id' => 9, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'active' => true],
            ['id' => 10, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Cayman Islands', 'iso2' => 'KY', 'iso3' => 'CYM', 'active' => true],
            ['id' => 11, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'active' => true],
            ['id' => 12, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'active' => true],
            ['id' => 13, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Curaçao', 'iso2' => 'CW', 'iso3' => 'CUW', 'active' => true],
            ['id' => 14, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'active' => true],
            ['id' => 15, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'active' => true],
            ['id' => 16, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'active' => true],
            ['id' => 17, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'active' => true],
            ['id' => 18, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'active' => true],
            ['id' => 19, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'active' => true],
            ['id' => 20, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'active' => true],
            ['id' => 21, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'active' => true],
            ['id' => 22, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'active' => true],
            ['id' => 23, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'active' => true],
            ['id' => 24, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Montserrat', 'iso2' => 'MS', 'iso3' => 'MSR', 'active' => true],
            ['id' => 25, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'active' => true],
            ['id' => 26, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'active' => true],
            ['id' => 27, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Puerto Rico', 'iso2' => 'PR', 'iso3' => 'PRI', 'active' => true],
            ['id' => 28, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'active' => true],
            ['id' => 29, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'active' => true],
            ['id' => 30, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'active' => true],
            ['id' => 31, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Sint Maarten', 'iso2' => 'SX', 'iso3' => 'SXM', 'active' => true],
            ['id' => 32, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'active' => true],
            ['id' => 33, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'active' => true],
            ['id' => 34, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'Turks and Caicos Islands', 'iso2' => 'TC', 'iso3' => 'TCA', 'active' => true],
            ['id' => 35, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'United States', 'iso2' => 'US', 'iso3' => 'USA', 'active' => true],
            ['id' => 36, 'confederation_id' => 1, 'region' => 'North/Central America & Caribbean', 'name' => 'United States Virgin Islands', 'iso2' => 'VI', 'iso3' => 'VIR', 'active' => true],
            ['id' => 37, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'active' => true],
            ['id' => 38, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'active' => true],
            ['id' => 39, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'active' => true],
            ['id' => 40, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'active' => true],
            ['id' => 41, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'active' => true],
            ['id' => 42, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'active' => true],
            ['id' => 43, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'active' => true],
            ['id' => 44, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'active' => true],
            ['id' => 45, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'active' => true],
            ['id' => 46, 'confederation_id' => 2, 'region' => 'South America', 'name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'active' => true],
            ['id' => 47, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'active' => true],
            ['id' => 48, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'active' => true],
            ['id' => 49, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'active' => true],
            ['id' => 50, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'active' => true],
            ['id' => 51, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'active' => true],
            ['id' => 52, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'active' => true],
            ['id' => 53, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'active' => true],
            ['id' => 54, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'active' => true],
            ['id' => 55, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'active' => true],
            ['id' => 56, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'active' => true],
            ['id' => 57, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'active' => true],
            ['id' => 58, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Czechia', 'iso2' => 'CZ', 'iso3' => 'CZE', 'active' => true],
            ['id' => 59, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'active' => true],
            ['id' => 60, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'England', 'iso2' => 'GB-ENG', 'iso3' => 'ENG', 'active' => true],
            ['id' => 61, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'active' => true],
            ['id' => 62, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Faroe Islands', 'iso2' => 'FO', 'iso3' => 'FRO', 'active' => true],
            ['id' => 63, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'active' => true],
            ['id' => 64, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'active' => true],
            ['id' => 65, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'active' => true],
            ['id' => 66, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'active' => true],
            ['id' => 67, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Gibraltar', 'iso2' => 'GI', 'iso3' => 'GIB', 'active' => true],
            ['id' => 68, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'active' => true],
            ['id' => 69, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'active' => true],
            ['id' => 70, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'active' => true],
            ['id' => 71, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'active' => true],
            ['id' => 72, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'active' => true],
            ['id' => 73, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'active' => true],
            ['id' => 74, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Kosovo', 'iso2' => 'XK', 'iso3' => 'XKX', 'active' => true],
            ['id' => 75, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'active' => true],
            ['id' => 76, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'active' => true],
            ['id' => 77, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'active' => true],
            ['id' => 78, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'active' => true],
            ['id' => 79, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'active' => true],
            ['id' => 80, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'active' => true],
            ['id' => 81, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'active' => true],
            ['id' => 82, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'North Macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'active' => true],
            ['id' => 83, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Northern Ireland', 'iso2' => 'GB-NIR', 'iso3' => 'NIR', 'active' => true],
            ['id' => 84, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'active' => true],
            ['id' => 85, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'active' => true],
            ['id' => 86, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'active' => true],
            ['id' => 87, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Republic of Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'active' => true],
            ['id' => 88, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'active' => true],
            ['id' => 89, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Russia', 'iso2' => 'RU', 'iso3' => 'RUS', 'active' => true],
            ['id' => 90, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'active' => true],
            ['id' => 91, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Scotland', 'iso2' => 'GB-SCT', 'iso3' => 'SCO', 'active' => true],
            ['id' => 92, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'active' => true],
            ['id' => 93, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'active' => true],
            ['id' => 94, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'active' => true],
            ['id' => 95, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'active' => true],
            ['id' => 96, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'active' => true],
            ['id' => 97, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'active' => true],
            ['id' => 98, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Türkiye', 'iso2' => 'TR', 'iso3' => 'TUR', 'active' => true],
            ['id' => 99, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'active' => true],
            ['id' => 100, 'confederation_id' => 3, 'region' => 'Europe', 'name' => 'Wales', 'iso2' => 'GB-WLS', 'iso3' => 'WAL', 'active' => true],
        ];

        $leagues = [
            ['id' => 1, 'country_id' => 1, 'name' => 'AFA Senior Male League', 'slug' => 'anguilla-afa-senior-male-league', 'active' => true],
            ['id' => 2, 'country_id' => 2, 'name' => 'ABFA Premier Division', 'slug' => 'antigua-and-barbuda-abfa-premier-division', 'active' => true],
            ['id' => 3, 'country_id' => 3, 'name' => 'Aruban Division di Honor', 'slug' => 'aruba-aruban-division-di-honor', 'active' => true],
            ['id' => 4, 'country_id' => 4, 'name' => 'Bahamas Senior League', 'slug' => 'bahamas-bahamas-senior-league', 'active' => true],
            ['id' => 5, 'country_id' => 5, 'name' => 'Barbados Premier League', 'slug' => 'barbados-barbados-premier-league', 'active' => true],
            ['id' => 6, 'country_id' => 6, 'name' => 'Premier League of Belize', 'slug' => 'belize-premier-league-of-belize', 'active' => true],
            ['id' => 7, 'country_id' => 7, 'name' => 'Bermudian Premier Division', 'slug' => 'bermuda-bermudian-premier-division', 'active' => true],
            ['id' => 8, 'country_id' => 8, 'name' => 'BVIFA National Football League', 'slug' => 'british-virgin-islands-bvifa-national-football-league', 'active' => true],
            ['id' => 9, 'country_id' => 9, 'name' => 'Canadian Premier League', 'slug' => 'canada-canadian-premier-league', 'active' => true],
            ['id' => 10, 'country_id' => 10, 'name' => 'Cayman Islands Premier League', 'slug' => 'cayman-islands-cayman-islands-premier-league', 'active' => true],
            ['id' => 11, 'country_id' => 11, 'name' => 'Liga FPD', 'slug' => 'costa-rica-liga-fpd', 'active' => true],
            ['id' => 12, 'country_id' => 11, 'name' => 'Liga de Ascenso Costa Rica', 'slug' => 'costa-rica-liga-de-ascenso-costa-rica', 'active' => true],
            ['id' => 13, 'country_id' => 12, 'name' => 'Campeonato Nacional de Fútbol de Cuba', 'slug' => 'cuba-campeonato-nacional-de-futbol-de-cuba', 'active' => true],
            ['id' => 14, 'country_id' => 13, 'name' => 'Curaçao Promé Divishon', 'slug' => 'curacao-curacao-prome-divishon', 'active' => true],
            ['id' => 15, 'country_id' => 14, 'name' => 'Dominica Premier League', 'slug' => 'dominica-dominica-premier-league', 'active' => true],
            ['id' => 16, 'country_id' => 15, 'name' => 'Liga Dominicana de Fútbol', 'slug' => 'dominican-republic-liga-dominicana-de-futbol', 'active' => true],
            ['id' => 17, 'country_id' => 16, 'name' => 'Primera División de El Salvador', 'slug' => 'el-salvador-primera-division-de-el-salvador', 'active' => true],
            ['id' => 18, 'country_id' => 16, 'name' => 'Segunda División de El Salvador', 'slug' => 'el-salvador-segunda-division-de-el-salvador', 'active' => true],
            ['id' => 19, 'country_id' => 17, 'name' => 'GFA Premier League', 'slug' => 'grenada-gfa-premier-league', 'active' => true],
            ['id' => 20, 'country_id' => 18, 'name' => 'Liga Nacional de Guatemala', 'slug' => 'guatemala-liga-nacional-de-guatemala', 'active' => true],
            ['id' => 21, 'country_id' => 18, 'name' => 'Primera División de Guatemala', 'slug' => 'guatemala-primera-division-de-guatemala', 'active' => true],
            ['id' => 22, 'country_id' => 19, 'name' => 'GFF Elite League', 'slug' => 'guyana-gff-elite-league', 'active' => true],
            ['id' => 23, 'country_id' => 20, 'name' => 'Ligue Haïtienne', 'slug' => 'haiti-ligue-haitienne', 'active' => true],
            ['id' => 24, 'country_id' => 21, 'name' => 'Liga Nacional de Honduras', 'slug' => 'honduras-liga-nacional-de-honduras', 'active' => true],
            ['id' => 25, 'country_id' => 21, 'name' => 'Liga de Ascenso de Honduras', 'slug' => 'honduras-liga-de-ascenso-de-honduras', 'active' => true],
            ['id' => 26, 'country_id' => 22, 'name' => 'Jamaica Premier League', 'slug' => 'jamaica-jamaica-premier-league', 'active' => true],
            ['id' => 27, 'country_id' => 23, 'name' => 'Liga MX', 'slug' => 'mexico-liga-mx', 'active' => true],
            ['id' => 28, 'country_id' => 23, 'name' => 'Liga Premier de México', 'slug' => 'mexico-liga-premier-de-mexico', 'active' => true],
            ['id' => 29, 'country_id' => 23, 'name' => 'Liga de Expansión MX', 'slug' => 'mexico-liga-de-expansion-mx', 'active' => true],
            ['id' => 30, 'country_id' => 24, 'name' => 'Montserrat Championship', 'slug' => 'montserrat-montserrat-championship', 'active' => true],
            ['id' => 31, 'country_id' => 25, 'name' => 'Liga Primera de Nicaragua', 'slug' => 'nicaragua-liga-primera-de-nicaragua', 'active' => true],
            ['id' => 32, 'country_id' => 25, 'name' => 'Liga de Ascenso de Nicaragua', 'slug' => 'nicaragua-liga-de-ascenso-de-nicaragua', 'active' => true],
            ['id' => 33, 'country_id' => 26, 'name' => 'Liga Panameña de Fútbol', 'slug' => 'panama-liga-panamena-de-futbol', 'active' => true],
            ['id' => 34, 'country_id' => 26, 'name' => 'Liga Prom', 'slug' => 'panama-liga-prom', 'active' => true],
            ['id' => 35, 'country_id' => 27, 'name' => 'Liga Puerto Rico', 'slug' => 'puerto-rico-liga-puerto-rico', 'active' => true],
            ['id' => 36, 'country_id' => 28, 'name' => 'SKNFA Premier League', 'slug' => 'saint-kitts-and-nevis-sknfa-premier-league', 'active' => true],
            ['id' => 37, 'country_id' => 29, 'name' => 'Saint Lucia First Division', 'slug' => 'saint-lucia-saint-lucia-first-division', 'active' => true],
            ['id' => 38, 'country_id' => 30, 'name' => 'NLA Premier League', 'slug' => 'saint-vincent-and-the-grenadines-nla-premier-league', 'active' => true],
            ['id' => 39, 'country_id' => 31, 'name' => 'Sint Maarten Premier League', 'slug' => 'sint-maarten-sint-maarten-premier-league', 'active' => true],
            ['id' => 40, 'country_id' => 32, 'name' => 'Suriname Major League', 'slug' => 'suriname-suriname-major-league', 'active' => true],
            ['id' => 41, 'country_id' => 33, 'name' => 'TT Premier Football League', 'slug' => 'trinidad-and-tobago-tt-premier-football-league', 'active' => true],
            ['id' => 42, 'country_id' => 34, 'name' => 'WIV Provo Premier League', 'slug' => 'turks-and-caicos-islands-wiv-provo-premier-league', 'active' => true],
            ['id' => 43, 'country_id' => 35, 'name' => 'MLS Next Pro', 'slug' => 'united-states-mls-next-pro', 'active' => true],
            ['id' => 44, 'country_id' => 35, 'name' => 'Major League Soccer', 'slug' => 'united-states-major-league-soccer', 'active' => true],
            ['id' => 45, 'country_id' => 35, 'name' => 'USL Championship', 'slug' => 'united-states-usl-championship', 'active' => true],
            ['id' => 46, 'country_id' => 35, 'name' => 'USL League One', 'slug' => 'united-states-usl-league-one', 'active' => true],
            ['id' => 47, 'country_id' => 36, 'name' => 'U.S. Virgin Islands Association Club Championship', 'slug' => 'united-states-virgin-islands-u-s-virgin-islands-association-club-championship', 'active' => true],
            ['id' => 48, 'country_id' => 37, 'name' => 'Liga Profesional de Fútbol', 'slug' => 'argentina-liga-profesional-de-futbol', 'active' => true],
            ['id' => 49, 'country_id' => 37, 'name' => 'Primera B Metropolitana', 'slug' => 'argentina-primera-b-metropolitana', 'active' => true],
            ['id' => 50, 'country_id' => 37, 'name' => 'Primera Nacional', 'slug' => 'argentina-primera-nacional', 'active' => true],
            ['id' => 51, 'country_id' => 37, 'name' => 'Torneo Federal A', 'slug' => 'argentina-torneo-federal-a', 'active' => true],
            ['id' => 52, 'country_id' => 38, 'name' => 'División Profesional', 'slug' => 'bolivia-division-profesional', 'active' => true],
            ['id' => 53, 'country_id' => 39, 'name' => 'Campeonato Brasileiro Série A', 'slug' => 'brazil-campeonato-brasileiro-serie-a', 'active' => true],
            ['id' => 54, 'country_id' => 39, 'name' => 'Campeonato Brasileiro Série B', 'slug' => 'brazil-campeonato-brasileiro-serie-b', 'active' => true],
            ['id' => 55, 'country_id' => 39, 'name' => 'Campeonato Brasileiro Série C', 'slug' => 'brazil-campeonato-brasileiro-serie-c', 'active' => true],
            ['id' => 56, 'country_id' => 39, 'name' => 'Campeonato Brasileiro Série D', 'slug' => 'brazil-campeonato-brasileiro-serie-d', 'active' => true],
            ['id' => 57, 'country_id' => 40, 'name' => 'Primera B de Chile', 'slug' => 'chile-primera-b-de-chile', 'active' => true],
            ['id' => 58, 'country_id' => 40, 'name' => 'Primera División de Chile', 'slug' => 'chile-primera-division-de-chile', 'active' => true],
            ['id' => 59, 'country_id' => 40, 'name' => 'Segunda División Profesional de Chile', 'slug' => 'chile-segunda-division-profesional-de-chile', 'active' => true],
            ['id' => 60, 'country_id' => 41, 'name' => 'Categoría Primera A', 'slug' => 'colombia-categoria-primera-a', 'active' => true],
            ['id' => 61, 'country_id' => 41, 'name' => 'Categoría Primera B', 'slug' => 'colombia-categoria-primera-b', 'active' => true],
            ['id' => 62, 'country_id' => 42, 'name' => 'LigaPro Serie A', 'slug' => 'ecuador-ligapro-serie-a', 'active' => true],
            ['id' => 63, 'country_id' => 42, 'name' => 'LigaPro Serie B', 'slug' => 'ecuador-ligapro-serie-b', 'active' => true],
            ['id' => 64, 'country_id' => 43, 'name' => 'División Intermedia', 'slug' => 'paraguay-division-intermedia', 'active' => true],
            ['id' => 65, 'country_id' => 43, 'name' => 'Primera División de Paraguay', 'slug' => 'paraguay-primera-division-de-paraguay', 'active' => true],
            ['id' => 66, 'country_id' => 44, 'name' => 'Liga 1 Peru', 'slug' => 'peru-liga-1-peru', 'active' => true],
            ['id' => 67, 'country_id' => 44, 'name' => 'Liga 2 Peru', 'slug' => 'peru-liga-2-peru', 'active' => true],
            ['id' => 68, 'country_id' => 45, 'name' => 'Primera División de Uruguay', 'slug' => 'uruguay-primera-division-de-uruguay', 'active' => true],
            ['id' => 69, 'country_id' => 45, 'name' => 'Segunda División Profesional de Uruguay', 'slug' => 'uruguay-segunda-division-profesional-de-uruguay', 'active' => true],
            ['id' => 70, 'country_id' => 46, 'name' => 'Primera División de Venezuela', 'slug' => 'venezuela-primera-division-de-venezuela', 'active' => true],
            ['id' => 71, 'country_id' => 46, 'name' => 'Segunda División de Venezuela', 'slug' => 'venezuela-segunda-division-de-venezuela', 'active' => true],
            ['id' => 72, 'country_id' => 47, 'name' => 'Kategoria Superiore', 'slug' => 'albania-kategoria-superiore', 'active' => true],
            ['id' => 73, 'country_id' => 47, 'name' => 'Kategoria e Parë', 'slug' => 'albania-kategoria-e-pare', 'active' => true],
            ['id' => 74, 'country_id' => 48, 'name' => 'Primera Divisió', 'slug' => 'andorra-primera-divisio', 'active' => true],
            ['id' => 75, 'country_id' => 49, 'name' => 'Armenian Premier League', 'slug' => 'armenia-armenian-premier-league', 'active' => true],
            ['id' => 76, 'country_id' => 50, 'name' => '2. Liga', 'slug' => 'austria-2-liga', 'active' => true],
            ['id' => 77, 'country_id' => 50, 'name' => 'Austrian Bundesliga', 'slug' => 'austria-austrian-bundesliga', 'active' => true],
            ['id' => 78, 'country_id' => 51, 'name' => 'Azerbaijan Premier League', 'slug' => 'azerbaijan-azerbaijan-premier-league', 'active' => true],
            ['id' => 79, 'country_id' => 52, 'name' => 'Belarusian Premier League', 'slug' => 'belarus-belarusian-premier-league', 'active' => true],
            ['id' => 80, 'country_id' => 53, 'name' => 'Belgian Pro League', 'slug' => 'belgium-belgian-pro-league', 'active' => true],
            ['id' => 81, 'country_id' => 53, 'name' => 'Challenger Pro League', 'slug' => 'belgium-challenger-pro-league', 'active' => true],
            ['id' => 82, 'country_id' => 54, 'name' => 'Premier League of Bosnia and Herzegovina', 'slug' => 'bosnia-and-herzegovina-premier-league-of-bosnia-and-herzegovina', 'active' => true],
            ['id' => 83, 'country_id' => 55, 'name' => 'First Professional Football League', 'slug' => 'bulgaria-first-professional-football-league', 'active' => true],
            ['id' => 84, 'country_id' => 55, 'name' => 'Second Professional Football League', 'slug' => 'bulgaria-second-professional-football-league', 'active' => true],
            ['id' => 85, 'country_id' => 56, 'name' => 'Croatian Football League', 'slug' => 'croatia-croatian-football-league', 'active' => true],
            ['id' => 86, 'country_id' => 56, 'name' => 'First Football League', 'slug' => 'croatia-first-football-league', 'active' => true],
            ['id' => 87, 'country_id' => 57, 'name' => 'Cypriot First Division', 'slug' => 'cyprus-cypriot-first-division', 'active' => true],
            ['id' => 88, 'country_id' => 57, 'name' => 'Cypriot Second Division', 'slug' => 'cyprus-cypriot-second-division', 'active' => true],
            ['id' => 89, 'country_id' => 58, 'name' => 'Czech First League', 'slug' => 'czechia-czech-first-league', 'active' => true],
            ['id' => 90, 'country_id' => 58, 'name' => 'Czech National Football League', 'slug' => 'czechia-czech-national-football-league', 'active' => true],
            ['id' => 91, 'country_id' => 59, 'name' => 'Danish 1st Division', 'slug' => 'denmark-danish-1st-division', 'active' => true],
            ['id' => 92, 'country_id' => 59, 'name' => 'Danish Superliga', 'slug' => 'denmark-danish-superliga', 'active' => true],
            ['id' => 93, 'country_id' => 60, 'name' => 'EFL Championship', 'slug' => 'england-efl-championship', 'active' => true],
            ['id' => 94, 'country_id' => 60, 'name' => 'EFL League One', 'slug' => 'england-efl-league-one', 'active' => true],
            ['id' => 95, 'country_id' => 60, 'name' => 'EFL League Two', 'slug' => 'england-efl-league-two', 'active' => true],
            ['id' => 96, 'country_id' => 60, 'name' => 'National League', 'slug' => 'england-national-league', 'active' => true],
            ['id' => 97, 'country_id' => 60, 'name' => 'Premier League', 'slug' => 'england-premier-league', 'active' => true],
            ['id' => 98, 'country_id' => 61, 'name' => 'Esiliiga', 'slug' => 'estonia-esiliiga', 'active' => true],
            ['id' => 99, 'country_id' => 61, 'name' => 'Meistriliiga', 'slug' => 'estonia-meistriliiga', 'active' => true],
            ['id' => 100, 'country_id' => 62, 'name' => 'Faroe Islands Premier League', 'slug' => 'faroe-islands-faroe-islands-premier-league', 'active' => true],
            ['id' => 101, 'country_id' => 63, 'name' => 'Veikkausliiga', 'slug' => 'finland-veikkausliiga', 'active' => true],
            ['id' => 102, 'country_id' => 63, 'name' => 'Ykkösliiga', 'slug' => 'finland-ykkosliiga', 'active' => true],
            ['id' => 103, 'country_id' => 64, 'name' => 'Championnat National', 'slug' => 'france-championnat-national', 'active' => true],
            ['id' => 104, 'country_id' => 64, 'name' => 'Ligue 1', 'slug' => 'france-ligue-1', 'active' => true],
            ['id' => 105, 'country_id' => 64, 'name' => 'Ligue 2', 'slug' => 'france-ligue-2', 'active' => true],
            ['id' => 106, 'country_id' => 65, 'name' => 'Erovnuli Liga', 'slug' => 'georgia-erovnuli-liga', 'active' => true],
            ['id' => 107, 'country_id' => 65, 'name' => 'Erovnuli Liga 2', 'slug' => 'georgia-erovnuli-liga-2', 'active' => true],
            ['id' => 108, 'country_id' => 66, 'name' => '2. Bundesliga', 'slug' => 'germany-2-bundesliga', 'active' => true],
            ['id' => 109, 'country_id' => 66, 'name' => '3. Liga', 'slug' => 'germany-3-liga', 'active' => true],
            ['id' => 110, 'country_id' => 66, 'name' => 'Bundesliga', 'slug' => 'germany-bundesliga', 'active' => true],
            ['id' => 111, 'country_id' => 67, 'name' => 'Gibraltar Football League', 'slug' => 'gibraltar-gibraltar-football-league', 'active' => true],
            ['id' => 112, 'country_id' => 68, 'name' => 'Super League Greece', 'slug' => 'greece-super-league-greece', 'active' => true],
            ['id' => 113, 'country_id' => 68, 'name' => 'Super League Greece 2', 'slug' => 'greece-super-league-greece-2', 'active' => true],
            ['id' => 114, 'country_id' => 69, 'name' => 'Nemzeti Bajnokság I', 'slug' => 'hungary-nemzeti-bajnoksag-i', 'active' => true],
            ['id' => 115, 'country_id' => 69, 'name' => 'Nemzeti Bajnokság II', 'slug' => 'hungary-nemzeti-bajnoksag-ii', 'active' => true],
            ['id' => 116, 'country_id' => 70, 'name' => '1. deild karla', 'slug' => 'iceland-1-deild-karla', 'active' => true],
            ['id' => 117, 'country_id' => 70, 'name' => 'Besta deild karla', 'slug' => 'iceland-besta-deild-karla', 'active' => true],
            ['id' => 118, 'country_id' => 71, 'name' => 'Israeli Premier League', 'slug' => 'israel-israeli-premier-league', 'active' => true],
            ['id' => 119, 'country_id' => 71, 'name' => 'Liga Leumit', 'slug' => 'israel-liga-leumit', 'active' => true],
            ['id' => 120, 'country_id' => 72, 'name' => 'Serie A', 'slug' => 'italy-serie-a', 'active' => true],
            ['id' => 121, 'country_id' => 72, 'name' => 'Serie B', 'slug' => 'italy-serie-b', 'active' => true],
            ['id' => 122, 'country_id' => 72, 'name' => 'Serie C', 'slug' => 'italy-serie-c', 'active' => true],
            ['id' => 123, 'country_id' => 73, 'name' => 'Kazakhstan First League', 'slug' => 'kazakhstan-kazakhstan-first-league', 'active' => true],
            ['id' => 124, 'country_id' => 73, 'name' => 'Kazakhstan Premier League', 'slug' => 'kazakhstan-kazakhstan-premier-league', 'active' => true],
            ['id' => 125, 'country_id' => 74, 'name' => 'Football Superleague of Kosovo', 'slug' => 'kosovo-football-superleague-of-kosovo', 'active' => true],
            ['id' => 126, 'country_id' => 75, 'name' => 'Latvian First League', 'slug' => 'latvia-latvian-first-league', 'active' => true],
            ['id' => 127, 'country_id' => 75, 'name' => 'Latvian Higher League', 'slug' => 'latvia-latvian-higher-league', 'active' => true],
            ['id' => 128, 'country_id' => 76, 'name' => 'A Lyga', 'slug' => 'lithuania-a-lyga', 'active' => true],
            ['id' => 129, 'country_id' => 76, 'name' => 'I Lyga', 'slug' => 'lithuania-i-lyga', 'active' => true],
            ['id' => 130, 'country_id' => 77, 'name' => 'Luxembourg Division of Honour', 'slug' => 'luxembourg-luxembourg-division-of-honour', 'active' => true],
            ['id' => 131, 'country_id' => 77, 'name' => 'Luxembourg National Division', 'slug' => 'luxembourg-luxembourg-national-division', 'active' => true],
            ['id' => 132, 'country_id' => 78, 'name' => 'Maltese Challenge League', 'slug' => 'malta-maltese-challenge-league', 'active' => true],
            ['id' => 133, 'country_id' => 78, 'name' => 'Maltese Premier League', 'slug' => 'malta-maltese-premier-league', 'active' => true],
            ['id' => 134, 'country_id' => 79, 'name' => 'Liga 1 Moldova', 'slug' => 'moldova-liga-1-moldova', 'active' => true],
            ['id' => 135, 'country_id' => 79, 'name' => 'Moldovan Super Liga', 'slug' => 'moldova-moldovan-super-liga', 'active' => true],
            ['id' => 136, 'country_id' => 80, 'name' => 'Montenegrin First League', 'slug' => 'montenegro-montenegrin-first-league', 'active' => true],
            ['id' => 137, 'country_id' => 80, 'name' => 'Montenegrin Second League', 'slug' => 'montenegro-montenegrin-second-league', 'active' => true],
            ['id' => 138, 'country_id' => 81, 'name' => 'Eerste Divisie', 'slug' => 'netherlands-eerste-divisie', 'active' => true],
            ['id' => 139, 'country_id' => 81, 'name' => 'Eredivisie', 'slug' => 'netherlands-eredivisie', 'active' => true],
            ['id' => 140, 'country_id' => 82, 'name' => 'Macedonian First Football League', 'slug' => 'north-macedonia-macedonian-first-football-league', 'active' => true],
            ['id' => 141, 'country_id' => 82, 'name' => 'Macedonian Second Football League', 'slug' => 'north-macedonia-macedonian-second-football-league', 'active' => true],
            ['id' => 142, 'country_id' => 83, 'name' => 'NIFL Championship', 'slug' => 'northern-ireland-nifl-championship', 'active' => true],
            ['id' => 143, 'country_id' => 83, 'name' => 'NIFL Premiership', 'slug' => 'northern-ireland-nifl-premiership', 'active' => true],
            ['id' => 144, 'country_id' => 84, 'name' => 'Eliteserien', 'slug' => 'norway-eliteserien', 'active' => true],
            ['id' => 145, 'country_id' => 84, 'name' => 'Norwegian First Division', 'slug' => 'norway-norwegian-first-division', 'active' => true],
            ['id' => 146, 'country_id' => 85, 'name' => 'Ekstraklasa', 'slug' => 'poland-ekstraklasa', 'active' => true],
            ['id' => 147, 'country_id' => 85, 'name' => 'I liga', 'slug' => 'poland-i-liga', 'active' => true],
            ['id' => 148, 'country_id' => 85, 'name' => 'II liga', 'slug' => 'poland-ii-liga', 'active' => true],
            ['id' => 149, 'country_id' => 86, 'name' => 'Liga 3', 'slug' => 'portugal-liga-3', 'active' => true],
            ['id' => 150, 'country_id' => 86, 'name' => 'Liga Portugal 2', 'slug' => 'portugal-liga-portugal-2', 'active' => true],
            ['id' => 151, 'country_id' => 86, 'name' => 'Primeira Liga', 'slug' => 'portugal-primeira-liga', 'active' => true],
            ['id' => 152, 'country_id' => 87, 'name' => 'League of Ireland First Division', 'slug' => 'republic-of-ireland-league-of-ireland-first-division', 'active' => true],
            ['id' => 153, 'country_id' => 87, 'name' => 'League of Ireland Premier Division', 'slug' => 'republic-of-ireland-league-of-ireland-premier-division', 'active' => true],
            ['id' => 154, 'country_id' => 88, 'name' => 'Liga I', 'slug' => 'romania-liga-i', 'active' => true],
            ['id' => 155, 'country_id' => 88, 'name' => 'Liga II', 'slug' => 'romania-liga-ii', 'active' => true],
            ['id' => 156, 'country_id' => 89, 'name' => 'Russian First League', 'slug' => 'russia-russian-first-league', 'active' => true],
            ['id' => 157, 'country_id' => 89, 'name' => 'Russian Premier League', 'slug' => 'russia-russian-premier-league', 'active' => true],
            ['id' => 158, 'country_id' => 90, 'name' => 'Campionato Sammarinese di Calcio', 'slug' => 'san-marino-campionato-sammarinese-di-calcio', 'active' => true],
            ['id' => 159, 'country_id' => 91, 'name' => 'Scottish Championship', 'slug' => 'scotland-scottish-championship', 'active' => true],
            ['id' => 160, 'country_id' => 91, 'name' => 'Scottish League One', 'slug' => 'scotland-scottish-league-one', 'active' => true],
            ['id' => 161, 'country_id' => 91, 'name' => 'Scottish League Two', 'slug' => 'scotland-scottish-league-two', 'active' => true],
            ['id' => 162, 'country_id' => 91, 'name' => 'Scottish Premiership', 'slug' => 'scotland-scottish-premiership', 'active' => true],
            ['id' => 163, 'country_id' => 92, 'name' => 'Serbian First League', 'slug' => 'serbia-serbian-first-league', 'active' => true],
            ['id' => 164, 'country_id' => 92, 'name' => 'Serbian SuperLiga', 'slug' => 'serbia-serbian-superliga', 'active' => true],
            ['id' => 165, 'country_id' => 93, 'name' => '2. Liga Slovakia', 'slug' => 'slovakia-2-liga-slovakia', 'active' => true],
            ['id' => 166, 'country_id' => 93, 'name' => 'Slovak First Football League', 'slug' => 'slovakia-slovak-first-football-league', 'active' => true],
            ['id' => 167, 'country_id' => 94, 'name' => 'Slovenian PrvaLiga', 'slug' => 'slovenia-slovenian-prvaliga', 'active' => true],
            ['id' => 168, 'country_id' => 94, 'name' => 'Slovenian Second League', 'slug' => 'slovenia-slovenian-second-league', 'active' => true],
            ['id' => 169, 'country_id' => 95, 'name' => 'La Liga', 'slug' => 'spain-la-liga', 'active' => true],
            ['id' => 170, 'country_id' => 95, 'name' => 'Primera Federación', 'slug' => 'spain-primera-federacion', 'active' => true],
            ['id' => 171, 'country_id' => 95, 'name' => 'Segunda División', 'slug' => 'spain-segunda-division', 'active' => true],
            ['id' => 172, 'country_id' => 96, 'name' => 'Allsvenskan', 'slug' => 'sweden-allsvenskan', 'active' => true],
            ['id' => 173, 'country_id' => 96, 'name' => 'Superettan', 'slug' => 'sweden-superettan', 'active' => true],
            ['id' => 174, 'country_id' => 97, 'name' => 'Swiss Challenge League', 'slug' => 'switzerland-swiss-challenge-league', 'active' => true],
            ['id' => 175, 'country_id' => 97, 'name' => 'Swiss Super League', 'slug' => 'switzerland-swiss-super-league', 'active' => true],
            ['id' => 176, 'country_id' => 98, 'name' => 'Süper Lig', 'slug' => 'turkiye-super-lig', 'active' => true],
            ['id' => 177, 'country_id' => 98, 'name' => 'TFF 1. Lig', 'slug' => 'turkiye-tff-1-lig', 'active' => true],
            ['id' => 178, 'country_id' => 98, 'name' => 'TFF 2. Lig', 'slug' => 'turkiye-tff-2-lig', 'active' => true],
            ['id' => 179, 'country_id' => 99, 'name' => 'Ukrainian First League', 'slug' => 'ukraine-ukrainian-first-league', 'active' => true],
            ['id' => 180, 'country_id' => 99, 'name' => 'Ukrainian Premier League', 'slug' => 'ukraine-ukrainian-premier-league', 'active' => true],
            ['id' => 181, 'country_id' => 100, 'name' => 'Cymru North', 'slug' => 'wales-cymru-north', 'active' => true],
            ['id' => 182, 'country_id' => 100, 'name' => 'Cymru Premier', 'slug' => 'wales-cymru-premier', 'active' => true],
            ['id' => 183, 'country_id' => 100, 'name' => 'Cymru South', 'slug' => 'wales-cymru-south', 'active' => true],
        ];

        DB::transaction(function () use ($confederations, $countries, $leagues, $now): void {
            DB::table('confederations')->upsert(
                array_map(fn (array $row) => $row + ['created_at' => $now, 'updated_at' => $now], $confederations),
                ['id'],
                ['code', 'name', 'active', 'updated_at']
            );

            foreach (array_chunk($countries, 200) as $chunk) {
                DB::table('countries')->upsert(
                    array_map(fn (array $row) => $row + ['created_at' => $now, 'updated_at' => $now], $chunk),
                    ['id'],
                    ['confederation_id', 'region', 'name', 'iso2', 'iso3', 'active', 'updated_at']
                );
            }

            foreach (array_chunk($leagues, 200) as $chunk) {
                DB::table('leagues')->upsert(
                    array_map(fn (array $row) => $row + ['created_at' => $now, 'updated_at' => $now], $chunk),
                    ['id'],
                    ['country_id', 'name', 'slug', 'active', 'updated_at']
                );
            }
        });
    }
}
